"""create gauge_configs

Revision ID: 21894e391f60
Revises:
Create Date: 2021-04-09 23:20:26.942742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "21894e391f60"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gauge_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("usgs_site", sa.String(length=32), nullable=False),
        sa.Column(
            "preferred_variable",
            sa.Enum("gage_height", "discharge", name="gaugevariableenum"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gauge_configs")
    # ### end Alembic commands ###
